language: go
go: 1.x
go_import_path: github.com/graphite-ng/carbon-relay-ng
script:
- make
- make test
before_deploy:
- tar cvzf carbon-relay-ng-${TRAVIS_TAG#?}-linux-amd64.tar.gz carbon-relay-ng
- "sha256sum carbon-relay-ng-*.tar.gz" > sha256
deploy:
  provider: releases
  api_key:
    secure: TurmngwFxQClajDOSkg8KBbLL7uKCtG+9GdIeZ5E4qoFpz1FFcJsoMqn/PjDPKxRa9DlrlAAX8G/n0k/J9aFDLFodazaRRwixtBZ0kzbEM+o+ANrxfMkDCds6c5tsaVDo2tZbGlDsnExKgsE8byhe6B/kf/iBJ7WqAv8wX72QUn0lQCuxrZpyibcQ4UX3AN202z5lvOxl2kKimOJjVfaqTGb1tLoILQYhdKNjxWpXVhlHDCEJIHJRDk27Oin/6rxTAhGhu6Vn/1gtHffTiGmpLDSN179WAcGB23v6El/RcbnaljoAMg8D/pjG7PYiYCJzObgHe48NDYqggT/Rr1DrAP7rjHRkSeGhq1iF5QNaHTjavgnpAALQ6spEagCYfoIypzTti+sIGQKwoIpbfdFug/oSJmAwP/HMqzMybYSsFSc8gXdzWgtthPBOMrO+BnBNbWVyyQALHH3jnMrkzi7pcnRk4WdZD9sYDB9mvcOjpGOQp9DkXPxgHB9eFhytJawFnO5Xm9+NZ7IlVUvdrxDFgLvRyrtkvYTdG06zgif7zIu59wr154az6J2/BV0WvXHGn51/t3KrbyQY5CxuIhg6KcK1fG5MBwvO4lnUdEPZz5rNt9QeoglbXr6rNPrd8sTzAGAEOh6JHZTt/6baRHrpEGDIda0ufuv4Uu6VbQEiY4=
  file: 
   - "carbon-relay-ng-${TRAVIS_TAG#?}-linux-amd64.tar.gz"
   - "sha256"
  skip_cleanup: true
  on:
    repo: criteo-forks/carbon-relay-ng
    tags: true
