language: go
go: 1.11.x
go_import_path: github.com/graphite-ng/carbon-relay-ng
script:
- make
- make test
before_deploy:
- tar cvzf carbon-relay-ng-${TRAVIS_TAG#?}-linux-amd64.tar.gz carbon-relay-ng
deploy:
  provider: releases
  api_key:
    secure:
      secure: zlfEQofpZoFRrKUW+8/n5sz76Y7Rx35ZzXbrnfROqGnxRyGrf+1h6T8yav2vq9CVLxvk+mAvOH5SzpLIGwBJ0zcXXLWkQlY5wZoaJicpMPICYdH2hOkR8/+pRxZlep77elIukirmYuFj+UbjPEsZsKt0saq2Dj7NzfuGyLkVnReu91+gGfnY+YbZJ9QaDUvh4LR4Ew0DsZwciDzz8/voHYE3Pf3xkaA3AokobN7FmMaLXKywDwvH/KIv0HeL2UcBSs1m4K4sx0Pyanmys99aiqIOuCPHPz2fg3THU/U0s8e5yxFcFcwV2RT9a9j/muiWy+z5/uQYabcKYXwpJIiIk0slYbHHVl9vgy8nM7E4XNcopbofDM8UD8a19HiPTJv82oSSA5UCVnwlcLWKcg22y5y5S4pNqypFPYWH6gM3Dd4YjaXX3s6dc8u5ca35+/T1iRvKl9QU6DfnXz3+AkwTpOHMmiGGa9S6ATst8JVYHAOTljfHeyiti9Jr0xHjNfWPsyV6K4j/+hOnL4y9DOGpOQ1JowdVU2glacnbTMjzyLazb9c7FVvmJ+4c0p/2WGle0/bKxSDtQ5JdxSEReroW2kX16v7a78CAd2Z+wY1Zt1YjHIJEDKkpWSmUz6IswzC3jXJQdHrD39z9KS72+vGCeMAt6HdBgZXaoLkurJMJlKk=
  file: carbon-relay-ng-${TRAVIS_TAG#?}-linux-amd64.tar.gz
  skip_cleanup: true
  on:
    repo: criteo-forks/carbon-relay-ng
    tags: true
