name: Builds and Releases

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.12.0'

      - name: Build
        run: make

      - name: Test
        run: make test
      
      - name: Bundle
        run: tar cvzf carbon-relay-ng-${{github.ref_name}}-linux-amd64.tar.gz carbon-relay-ng

      - name: Checksum
        run: echo `sha256sum carbon-relay-ng-*.tar.gz` > sha256
      

      - name: Publish Artifact
        uses: actions/upload-artifact@v3
        with:
          name: carbon-relay-ng-${{github.ref_name}}-linux-amd64.tar.gz
          path: carbon-relay-ng-${{github.ref_name}}-linux-amd64.tar.gz
      
      - name: Publish Checksum
        uses: actions/upload-artifact@v3
        with:
          name: sha256
          path: sha256